tango_with_django/rango/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    url(r'^restricted/', views.restricted, name='restricted'),
    url(r'^search/$', views.search, name='search'),
]

tango_with_django/tango_with_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from registration.backends.simple.views import RegistrationView

from rango import views


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/rango/'


urlpatterns = [
    url(r'^rango/', include('rango.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    likes = models.IntegerField(default=0)
    views = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

tango_with_django/rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from  django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text='Please enter the category name')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text='Please enter the title of the page')
    url = forms.URLField(max_length=200,
                         help_text='Please enter the URL of the page')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

tango_with_django/rango/views.py
from datetime import datetime
from django.shortcuts import render
from django.core.urlresolvers import reverse
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from rango.models import Category, Page
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from rango.bing_search import run_query


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))

    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1

        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits

def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    pages_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories': category_list, 'pages': pages_list}

    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    response = render(request, 'rango/index.html', context_dict)
    return response


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)

        context_dict['category'] = category
        context_dict['pages'] = pages

    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context_dict)


def about(request):
    visitor_cookie_handler(request)

    return render(request, 'rango/about.html', {'visits': request.session['visits']})

@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == "POST":
        form = CategoryForm(request.POST)

        if form.is_valid():
            form.save(commit=True)

            return index(request)

        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return  show_category(request, category_name_slug)
        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return  render(request,
                   'rango/register.html',
                   {'user_form': user_form,
                    'profile_form': profile_form,
                    'registered': registered})


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('rango:index'))
            else:
                return HttpResponse('Your Rango account is disabled.')

        else:
            print('Invalid login details: {0}, {1}'.format(username,password))
            return HttpResponse('Invalid login details supplied.')

    else:
        return render(request, 'rango/login.html', {})


@login_required
def restricted(request):
    return render(request, 'rango/restricted.html', {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('rango:index'))


def search(request):
    result_list = []
    context_dict = {}
    if request.method == "POST":
        query = request.POST['query'].strip()
        context_dict['query'] = query
        if query:
            result_list = run_query(query)
            context_dict['result_list'] = result_list

    return render(request, 'rango/search.html', context_dict)

tango_with_django/templates/rango/about.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}
{% block title_block %}
ABOUT
{% endblock %}
{% block body_block %}
<h1>This page made by <a href="/">RAVEN</a></h1>
<h2>You are visited this site {{ visits }} time{{ visits|pluralize }}</h2>
{% endblock %}

tango_with_django/templates/rango/add_category.html
{% extends 'rango/base_bootstrap.html' %}
{% load bootstrap_toolkit %}
{% block title %}Add category{% endblock %}

{% block body_block %}
    <form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
        <h2 class="form-singin-heading">Add a Category</h2>
        {% csrf_token %}
        {{ form|as_bootstrap }}

        <button class="btn btn-primary" type="submit" name="submit">Add category</button>
    </form>
{% endblock %}

tango_with_django/templates/rango/add_page.html
{% extends 'rango/base_bootstrap.html' %}
{% block title %}Add page{% endblock %}

{% block body_block %}
    {% if category %}
        <form role="form" id="page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
            <h2 class="form-signin-heading">Add a Page to <a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a> </h2>
            {% csrf_token %}
            {% for hidden_field in form.hidden_fields %}
                    {{ hidden_field }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br>
                {{ field }}<br>
            {% endfor %}
            <br>
            <button class="btn btn-primary" type="submit" name="submit">
                Add Page
            </button>
        </form>
        {% else %}
        <p>This is categoty does not exist</p>
    {% endif %}
{% endblock %}

tango_with_django/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        Rango -
        {% block title_block %}
            How to Tango with Django!
        {% endblock %}
    </title>
</head>
<body>
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
    </div>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    <hr>
    <div>
        <ul>
        {% if user.is_authenticated %}
            <li><a href="{% url 'rango:restricted' %}">Restricted Page</a> </li>
            <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a> </li>
            <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
            <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
        {% else %}
            <li><a href="{% url 'auth_login' %}">Sign in</a></li>
            <li><a href="{% url 'registration_register' %}">Sign up</a></li>
        {% endif %}
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
</body>
</html>

tango_with_django/templates/rango/base_bootstrap.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>
        Rango - {% block title %}How to Tango with Django!{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="http://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://v4-alpha.getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-dark navbar-fixed-top bg-inverse">
      <button type="button" class="navbar-toggler hidden-sm-up" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Rango</a>
      <div id="navbar">
        <nav class="nav navbar-nav pull-xs-left">
          <a class="nav-item nav-link" href="{% url 'rango:index' %}">Home</a>
          <a class="nav-item nav-link" href="{% url 'rango:about' %}">About</a>

          {% if user.is_authenticated %}
          <a class="nav-item nav-link" href="{% url 'rango:add_category' %}">Add a New Category</a>
          <a class="nav-item nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a>
          <a class="nav-item nav-link" href="{% url 'rango:search' %}">Search</a>
          {% else %}
          <a class="nav-item nav-link" href="{% url 'registration_register' %}">Register Here</a>
          <a class="nav-item nav-link" href="{% url 'auth_login' %}">Login</a>
          {% endif %}
        </nav>
      </div>
    </nav>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% block sidebar_block %}
            {% get_category_list category %}
          {% endblock %}
        </div>
        <div class="col-sm-9 offset-sm-3 col-md-10 offset-md-2 main">
          {% block body_block %}{% endblock %}
        </div>
        </div>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src='https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js'></script>
    <script src="http://v4-alpha.getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <script src="http://v4-alpha.getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

tango_with_django/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ category.name }}
{% endblock %}

{% block body_block %}
    {% if category %}
        <h1>{{ category.name }}</h1>

        {% if pages %}
            <ul>
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a> </li>
            {% endfor %}
            </ul>
        {% else %}
            <strong>There are no categories</strong>
        {% endif %}
        <a href="{% url 'rango:add_page' category.slug %}">Add a Page</a>
    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

tango_with_django/templates/rango/cats.html
<ul>
    {% if cats %}
        {% for c in cats %}
            {% if c == act_cat %}
            <li><strong><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></strong> </li>
        {% else %}
            <li><a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a></li>
        {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present</strong></li>
    {% endif %}
</ul>

tango_with_django/templates/rango/index.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}
{% block title %}
Index
{% endblock %}
{% block body_block %}
<div class="jumbotron">
    <h1 class="display-3">Rango says...</h1>
    {% if user.is_authenticated %}
        <h1>hey there {{ user.username }}</h1>
    {% else %}
        <h1>hey there partner! </h1>
    {% endif %}
</div>
<div class="row marketing">
    <div class="col-lg-6">
        <h4>Most Liked Categories</h4>
        <p>
            {% if categories %}
            <ul class="list-group">
                {% for category in categories %}
                <li class="list-group-item"><a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a> </li>
                {% endfor %}
            </ul>
            {% else %}
                <strong>There are no categories present.</strong>
            {% endif %}
        </p>
    </div>
    <div class="col-lg-6">
        <h4>Most Viewed Pages</h4>
        <p>
        {% if pages %}
        <ul class="list-group">
            {% for page in pages %}
            <li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a> </li>
            {% endfor %}
        </ul>
        {% else %}
            <strong>There are no pages present.</strong>
        {% endif %}
        </p>
    </div>
</div>
{% endblock %}

tango_with_django/templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50">
    <br>
    Password: <input type="password" name="password" value="" size="50">
    <br>
    <input type="submit" value="submit">
</form>
{% endblock %}

tango_with_django/templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <h1>About Page</h1>
    {% if registered %}
        Rango says: <strong>thank you for registering!</strong>
        <a href="{% url 'rango:index' %}">Return to homepage</a><br>
    {% else %}
        Rango says: <strong>register here!</strong><br>
        <form id="user_form" method="post" action="{% url 'rango:register' %}"
              enctype="multipart/form-data">

            {% csrf_token %}

            {{ user_form.as_p }}
            {{ profile_form.as_p }}

            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
{% endblock %}

tango_with_django/templates/rango/restricted.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

tango_with_django/templates/rango/search.html
{% extends 'rango/base_bootstrap.html' %}
{% load staticfiles %}

{% block title %} Search {% endblock %}

{% block body_block %}
<div>
    <h1>Search with Rango</h1>
    <br>
    <form class="form-inline" id="user_form" method="post" action="{% url 'rango:search' %}">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query">
        </div>
        <button class="btn btn-primary" type="submit" name="submit" value="Search">Search</button>
    </form>

<div>
    {% if result_list %}
    <h3>Results</h3>
    <div class="list-group">
    {% for result in result_list %}
        <div class="list-group-item">
            <h4 class="list-group-item-heading">
                <a href="{{ result.link }}">{{ result.title }}</a>
            </h4>
            <p class="list-group-item-text">{{ result.summary }}</p>
        </div>
    {% endfor %}
    </div>
    {% endif %}
</div>
</div>
{% endblock %}